package ru.ztrixdev.projects.passhavenapp.ui.theme.ubuntu
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF73153E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF912E55)
val onPrimaryContainerLight = Color(0xFFFFB1C8)
val secondaryLight = Color(0xFF82505F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFEBDCF)
val onSecondaryContainerLight = Color(0xFF7B4959)
val tertiaryLight = Color(0xFF6A2700)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF8F3700)
val onTertiaryContainerLight = Color(0xFFFFB695)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F8)
val onBackgroundLight = Color(0xFF23191B)
val surfaceLight = Color(0xFFFFF8F8)
val onSurfaceLight = Color(0xFF23191B)
val surfaceVariantLight = Color(0xFFF7DCE2)
val onSurfaceVariantLight = Color(0xFF554247)
val outlineLight = Color(0xFF877177)
val outlineVariantLight = Color(0xFFDAC0C6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E30)
val inverseOnSurfaceLight = Color(0xFFFFECEF)
val inversePrimaryLight = Color(0xFFFFB1C7)
val surfaceDimLight = Color(0xFFE8D6D9)
val surfaceBrightLight = Color(0xFFFFF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F2)
val surfaceContainerLight = Color(0xFFFCE9ED)
val surfaceContainerHighLight = Color(0xFFF6E4E7)
val surfaceContainerHighestLight = Color(0xFFF0DEE1)

val primaryDark = Color(0xFFFFB1C7)
val onPrimaryDark = Color(0xFF630532)
val primaryContainerDark = Color(0xFF912E55)
val onPrimaryContainerDark = Color(0xFFFFB1C8)
val secondaryDark = Color(0xFFF5B5C7)
val onSecondaryDark = Color(0xFF4D2331)
val secondaryContainerDark = Color(0xFF6A3B4A)
val onSecondaryContainerDark = Color(0xFFE6A7B9)
val tertiaryDark = Color(0xFFFFB695)
val onTertiaryDark = Color(0xFF571F00)
val tertiaryContainerDark = Color(0xFF8F3700)
val onTertiaryContainerDark = Color(0xFFFFB695)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1113)
val onBackgroundDark = Color(0xFFF0DEE1)
val surfaceDark = Color(0xFF1A1113)
val onSurfaceDark = Color(0xFFF0DEE1)
val surfaceVariantDark = Color(0xFF554247)
val onSurfaceVariantDark = Color(0xFFDAC0C6)
val outlineDark = Color(0xFFA28B90)
val outlineVariantDark = Color(0xFF554247)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF0DEE1)
val inverseOnSurfaceDark = Color(0xFF382E30)
val inversePrimaryDark = Color(0xFFA03A60)
val surfaceDimDark = Color(0xFF1A1113)
val surfaceBrightDark = Color(0xFF423639)
val surfaceContainerLowestDark = Color(0xFF140C0E)
val surfaceContainerLowDark = Color(0xFF23191B)
val surfaceContainerDark = Color(0xFF271D1F)
val surfaceContainerHighDark = Color(0xFF32272A)
val surfaceContainerHighestDark = Color(0xFF3D3235)



